# 넘파이
- ndim : 축의 개수
- shape : 배열의 차원정보
- size : 배열안에 있는 원소의 총 개수
- dtype : 배열 원소의 자료형

### 1차원과 속성들

In [2]:
list = [11, 22, 33, 44, 55]
import numpy as np
narr = np.array(range(7))
print(narr)
print(type(narr))
print(narr.ndim)
print(narr.shape)
print(narr.size)
print(narr.dtype)
print(narr[3])
print(narr[2:5])

[0 1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
(7,)
7
int64
3
[2 3 4]


In [3]:
narr1 = np.array([1, 2, 3, 4])  # int64
narr2 = np.array([1, 2, 'apple', 'banana'])
narr3 = np.array([1, 2, 3, 4], dtype='str')
print(narr1, narr1.dtype)
print(narr2, narr2.dtype)
print(narr3, narr3.dtype)

[1 2 3 4] int64
['1' '2' 'apple' 'banana'] <U21
['1' '2' '3' '4'] <U1


In [4]:
narr4 = np.zeros(10, dtype='int64')
narr5 = np.ones(10, dtype='int64')
narr6 = np.full(5, 2, dtype='float64')
narr7 = np.full(5, 'ok')
narr8 = np.linspace(0, 10, 5, endpoint=False)
narr9 = np.arange(10)
print(narr4, narr4.dtype)
print(narr5, narr5.dtype)
print(narr6, narr6.dtype)
print(narr7, narr7.dtype)
print(narr8, narr8.dtype)
print(narr9, narr9.dtype)

[0 0 0 0 0 0 0 0 0 0] int64
[1 1 1 1 1 1 1 1 1 1] int64
[2. 2. 2. 2. 2.] float64
['ok' 'ok' 'ok' 'ok' 'ok'] <U2
[0. 2. 4. 6. 8.] float64
[0 1 2 3 4 5 6 7 8 9] int64


In [5]:
# 2차원
arr1 = np.zeros((2, 2))
arr2 = np.ones((2, 2))
arr3 = np.full((2, 2), 5)
arr4 = np.eye(2)
print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)
print(arr4, arr4.dtype)

[[0. 0.]
 [0. 0.]] float64
[[1. 1.]
 [1. 1.]] float64
[[5 5]
 [5 5]] int64
[[1. 0.]
 [0. 1.]] float64


In [6]:
# 2차원 배열
nar = np.array([[1, 2], [3, 4]])
print(nar, nar.ndim, nar.dtype, nar.shape, nar.size, type(nar))

[[1 2]
 [3 4]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [7]:
# 2차원 타입변환
nar1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)
nar2 = np.arange(1, 10).reshape(3, 3)
nar3 = np.arange(1, 11).reshape(2, 5)
nar4 = np.arange(1, 11).reshape(5, 2)
nar5 = np.arange(1, 28).reshape(3 ,3 ,3)
print(nar1, nar1.ndim, nar1.dtype, nar1.shape, nar1.size, type(nar1))
print(nar2, nar2.ndim, nar2.dtype, nar2.shape, nar2.size, type(nar2))
print(nar3, nar3.ndim, nar3.dtype, nar3.shape, nar3.size, type(nar3))
print(nar4, nar4.ndim, nar4.dtype, nar4.shape, nar4.size, type(nar4))
print(nar5, nar5.ndim, nar5.dtype, nar5.shape, nar5.size, type(nar5))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 2 int64 (2, 5) 10 <class 'numpy.ndarray'>
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 2 int64 (5, 2) 10 <class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 3 int64 (3, 3, 3) 27 <class 'numpy.ndarray'>


In [8]:
t1 = np.arange(1, 22).reshape(3, 7)
t2 = np.arange(1, 8).reshape(7, 1)
t3 = np.arange(1, 11).reshape(5, 2)
t4 = np.arange(1, 13).reshape(4, 3, 1)

print(t1)
print("="*23)
print(t2)
print("="*23)
print(t3)
print("="*23)
print(t4)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [9]:
print(t1[1][2:5])
print(t1[1:3, 2:5])
# 브로드캐스팅
print(t1 *10)
print(t1 % 2 == 0)
print(t1[t1 % 2 == 0])

[10 11 12]
[[10 11 12]
 [17 18 19]]
[[ 10  20  30  40  50  60  70]
 [ 80  90 100 110 120 130 140]
 [150 160 170 180 190 200 210]]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]
[ 2  4  6  8 10 12 14 16 18 20]


In [10]:
l1 = [6, 7, 8, 9, 10]
l2 = [1, 2, 3, 4, 5]
print(l1 + l2)
np1 = np.array(l1)
np2 = np.array(l2)
np3 = np1 + np2
print(np3.tolist())
print("덧셈: ", np1 + np2)
print("뺄셈: ", np1 - np2)
print("곱셈: ", np1 * np2)
print("나눗셈: ", np1 / np2)

[6, 7, 8, 9, 10, 1, 2, 3, 4, 5]
[7, 9, 11, 13, 15]
덧셈:  [ 7  9 11 13 15]
뺄셈:  [5 5 5 5 5]
곱셈:  [ 6 14 24 36 50]
나눗셈:  [6.         3.5        2.66666667 2.25       2.        ]


In [11]:
# flatten 처리
ff = np.arange(1, 10).reshape(3, 3)
print(ff)
print(ff.reshape(9))
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


### Random number 발생
- np.random.randint(): 균일 분포의 정수 난수
- np.random.rand(): 0부터 1사이의 균일 분포 난수 생성
- np.random.randn(): 표준 정규 분포 난수 생성
- np.random.normal(): 정규 분포 난수 생성

In [12]:
# randomint
# RGB(세로픽셀수, 가로픽셀, 색상채널)
x = np.random.randint(0, 255, size=(3, 3, 3))
x

array([[[232, 158, 148],
        [213, 228,  48],
        [ 78, 192, 179]],

       [[ 89,  61, 146],
        [ 85, 128, 145],
        [198, 163,   7]],

       [[226, 136, 179],
        [ 46, 232,  94],
        [126, 196,   1]]])

In [14]:
print("평균값:", np.mean(x), "표준편차:", np.std(x), "최소값:", x.min(), "최대값:", x.max())

평균값: 138.2962962962963 표준편차: 67.50463074091853 최소값: 1 최대값: 232


In [15]:
x2 = np.random.normal(5, 3, (10, 5))  # 평균이 5, 표준편차가 3
x2

array([[ 7.76929299,  5.10289192,  3.2696889 ,  4.38697525,  4.37188776],
       [ 3.52535964,  5.44111375,  3.65118624,  6.40517935,  6.68077561],
       [11.1860606 ,  4.04590509,  5.99943149,  2.1297405 ,  7.43191352],
       [ 3.5608989 ,  9.7003944 ,  8.37092063, 10.03267292,  4.75754434],
       [-0.78388528,  6.75484828,  4.57254835,  4.89731917,  6.94863165],
       [ 2.57974858,  7.07378452,  2.97509294,  3.9724108 ,  4.68174244],
       [ 4.32109933, 15.29077826,  0.72184489,  5.78667545,  2.35171951],
       [ 2.03064816,  2.91752902,  3.70544178,  0.0307095 ,  4.87535191],
       [ 8.85604489,  7.03243675,  7.47230154,  5.12472999,  6.31916978],
       [ 3.49029475,  2.94146285,  3.41879508,  2.42821555,  6.71053608]])

In [16]:
x3 = np.random.randn(10, 5)  # 표준 정규 분포 난수 생성
x3

array([[ 0.54827848,  0.77034836,  2.31728715, -0.99173402, -0.20205828],
       [-1.09479151, -0.46514505, -0.95695022,  1.17117648,  0.48378805],
       [-0.46911103, -0.02037391,  0.19876342,  1.54663079,  0.22853618],
       [ 1.06081676,  1.22391313, -0.84957131, -1.11335262, -0.82866438],
       [ 1.16356503,  0.15789101, -0.15943163,  0.60726739,  0.73739708],
       [-0.01598974,  1.01116352,  0.77679946, -0.17423642, -0.62464859],
       [ 0.44834531,  1.06382275,  0.60236939,  0.20721125, -0.32462262],
       [ 0.95247696,  0.94731382, -0.98334937,  0.40136125,  0.38207113],
       [ 1.67745117, -2.76713741, -1.00115017, -0.94543319,  1.36212182],
       [-0.76213746,  0.96468178,  0.05209453,  0.09317375,  0.76565447]])

In [18]:
x4 = np.array([3, 1, 2, 3, 5, 0, 4, 5, 0, 44, 5, 0, 6, 0, 56, 0, 5, 60, 0, 5, 6])
print(len(x4))
print(np.count_nonzero(x4))
print(len(x4)-np.count_nonzero(x4))

21
15
6


In [22]:
print(np.mean(x2))  # 평균
print(x2.mean())
print(np.var(x2))  # 분산
print(x2.var())
print(np.std(x2))  # 표준편차
print(x2.std())
print(x2.min())  # 최소값
print(x2.max())  # 최대값
print(np.median(x2))  # 중간값

5.146357207030244
5.146357207030244
8.156061315255165
8.156061315255165
2.8558818804802075
2.8558818804802075
-0.7838852778553047
15.290778259208075
4.71964338781876


In [23]:
print(np.percentile(x2, 0))  # 최소값
print(np.percentile(x2, 25))  # 하위 25%, 제1사분위수
print(np.percentile(x2, 50))  # 중앙값, 제2사분위수
print(np.percentile(x2, 75))  # 상위 25%, 제3사분위수
print(np.percentile(x2, 100))  # 최대값

-0.7838852778553047
3.4366699943517167
4.71964338781876
6.743770233818298
15.290778259208075
